language: node_js
node_js:
- "stable"

after_success:
- npm run coveralls

# node_js:
#   - "0.12"
#   - iojs
#   - "4"
#   - "6"
#   - "stable"

# before_install:
#   # https://yarnpkg.com/en/docs/install_ci
#   - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#   - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
#   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#   - sudo apt-get update -qq
#   - sudo apt-get install -y -qq yarn
# cache:
#   directories:
#   - $HOME/.yarn-cache

# install: "yarn"

# script: "yarn run travis"

# after_success:
#   - yarn run test:coveralls
#   - rm -rf ./coverage