language: node_js
node_js:
- "stable"

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cross-env NODE_ENV=test sequelize db:migrate

after_success:
- npm run coveralls

notifications:
  email:
    on_failure: change