language: node_js
node_js:
- "stable"

NODE_ENV: test

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- sequelize db:migrate

after_success:
- npm run coveralls

notifications:
  email:
    on_failure: change