language: node_js
node_js:
- "stable"

env:
- DB=pgsql

services:
- postgresql

before_script:
- psql -c 'create database more_recipes_test;' -U postgres
- psql -c "CREATE USER TOBI WITH PASSWORD 'password';" -U postgres
- psql 'grant all privileges on database more_recipes_test to TOBI;'
- cross-env NODE_ENV=test sequelize db:migrate

after_success:
- npm run coveralls

notifications:
  email:
    on_failure: change