language: node_js
node_js:
- "stable"

env:
- DB=pgsql

services:
- postgresql

before_script:
- psql -c 'create database more_recipes_test;' -U postgres -w
- psql -c "CREATE ROLE TOBI WITH LOGIN PASSWORD 'password';" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE more_recipes_test TO TOBI;' -U postgres
- cross-env NODE_ENV=test sequelize db:migrate
- psql -c '\list' -U tobi
- psql -c '\du' -U tobi
- psql -c '\dt' -U tobi -d more_recipes_test

after_success:
- npm run coveralls

notifications:
  email:
    on_failure: change