export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE= 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START'; 
export const AUTH_SUCCESS = 'AUTH_SUCCESS'; 
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_TOGGLE_REGISTER_SIGNIN = 'AUTH_TOGGLE_REGISTER_SIGNIN';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const ADD_REVIEW = 'ADD_REVIEW';
export const REMOVE_REVIEW = 'REMOVE_REVIEW';
export const DISPLAY_VOTE_ON_ACTIVE_RECIPE = 'DISPLAY_VOTE_ON_ACTIVE_RECIPE';
export const REGISTER_VOTE_ON_SERVER_SUCCESS = 'REGISTER_VOTE_ON_SERVER_SUCCESS';
export const REGISTER_VOTE_ON_SERVER_FAILED = 'REGISTER_VOTE_ON_SERVER_FAILED';
export const FETCH_LATEST_RECIPES_START = 'FETCH_LATEST_RECIPES_START';
export const FETCH_LATEST_RECIPES_SUCCESS = 'FETCH_LATEST_RECIPES_SUCCESS';
export const FETCH_LATEST_RECIPES_FAILED = 'FETCH_LATEST_RECIPES_FAILED';
